server:
  port: 8081

spring:
  application:
    name: data-insight-user
  config:
    import: optional:nacos:${spring.application.name}.yaml
  datasource:
    url: jdbc:mysql://localhost:3306/data_insight_user?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:1234}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDR:localhost:8848}
      config:
        server-addr: ${NACOS_ADDR:localhost:8848}
        file-extension: yaml

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

data-insight:
  upload-dir: E:/ai训练/data-insight/uploads

logging:
  level:
    com.datainsight: debug
